package mc.monacotelecom.services.enums;

public enum ProvisioningProductActionRequest {
    FIRST_ACTIVATION, ACTIVATION, TRANSITION, MIGRATION, DEACTIVATION, CHGE_NUM, CHGE_EQT, RETURN_EQT, CHGE_ADDR,CHGE_CLI, BARRING, UNBARRING, SUSP_CLI, RESUM_CLI, SUSP_OPER, RESUM_OPER, RESET_CELL, RETURN_ANCIL, CHGE_ANCIL, TRANSFER, ADD_QTY, DEL_QTY, CHGE_MSISDN,  CHGE_OFFER
}
