keycloak.bearer-only=true
keycloak.cors=true
keycloak.auth-server-url=${KEYCLOAK_AUTH_SERVER_URL}
keycloak.credentials.secret=${KEYCLOAK_CREDENTIALS_SECRET}
keycloak.realm=${KEYCLOAK_REALM}
keycloak.resource=${KEYCLOAK_RESOURCE}
keycloak.ssl-required=external
keycloak.use-resource-role-mappings=true
keycloak.principal-attribute=preferred_username
keycloak.securityConstraints[0].authRoles[0]=SERVICE_READ
keycloak.securityConstraints[0].authRoles[1]=SERVICE_WRITE
keycloak.securityConstraints[0].authRoles[2]=SERVICE_DELETE
keycloak.securityConstraints[0].securityCollections[0].patterns[0]=/private/auth/*
keycloak.securityConstraints[0].securityCollections[0].patterns[1]=/api/v1/private/auth/*

# Standard APIs (Swagger, Monitoring...)
keycloak.policy-enforcer-config.paths[0].path=/*
keycloak.policy-enforcer-config.paths[0].enforcement-mode=DISABLED

# Service API
keycloak.policy-enforcer-config.paths[1].path=/private/auth/services/*
keycloak.policy-enforcer-config.paths[1].methods[0].method=POST
keycloak.policy-enforcer-config.paths[1].methods[0].scopes[0]=services_create
keycloak.policy-enforcer-config.paths[1].methods[1].method=GET
keycloak.policy-enforcer-config.paths[1].methods[1].scopes[0]=services_read
keycloak.policy-enforcer-config.paths[1].methods[2].method=PUT
keycloak.policy-enforcer-config.paths[1].methods[2].scopes[0]=services_update
keycloak.policy-enforcer-config.paths[1].methods[3].method=PATCH
keycloak.policy-enforcer-config.paths[1].methods[3].scopes[0]=services_update
keycloak.policy-enforcer-config.paths[1].methods[4].method=DELETE
keycloak.policy-enforcer-config.paths[1].methods[4].scopes[0]=services_delete

# Activation Code API
keycloak.policy-enforcer-config.paths[2].path=/private/auth/activationcodes/*
keycloak.policy-enforcer-config.paths[2].methods[0].method=POST
keycloak.policy-enforcer-config.paths[2].methods[0].scopes[0]=activationcodes_create
keycloak.policy-enforcer-config.paths[2].methods[1].method=GET
keycloak.policy-enforcer-config.paths[2].methods[1].scopes[0]=activationcodes_read
keycloak.policy-enforcer-config.paths[2].methods[2].method=PUT
keycloak.policy-enforcer-config.paths[2].methods[2].scopes[0]=activationcodes_update
keycloak.policy-enforcer-config.paths[2].methods[3].method=PATCH
keycloak.policy-enforcer-config.paths[2].methods[3].scopes[0]=activationcodes_update
keycloak.policy-enforcer-config.paths[2].methods[4].method=DELETE
keycloak.policy-enforcer-config.paths[2].methods[4].scopes[0]=activationcodes_delete

# Provisioning Tag API
keycloak.policy-enforcer-config.paths[3].path=/private/auth/provisioningtags/*
keycloak.policy-enforcer-config.paths[3].methods[0].method=POST
keycloak.policy-enforcer-config.paths[3].methods[0].scopes[0]=provisioningtags_create
keycloak.policy-enforcer-config.paths[3].methods[1].method=GET
keycloak.policy-enforcer-config.paths[3].methods[1].scopes[0]=provisioningtags_read
keycloak.policy-enforcer-config.paths[3].methods[2].method=PUT
keycloak.policy-enforcer-config.paths[3].methods[2].scopes[0]=provisioningtags_update
keycloak.policy-enforcer-config.paths[3].methods[3].method=PATCH
keycloak.policy-enforcer-config.paths[3].methods[3].scopes[0]=provisioningtags_update
keycloak.policy-enforcer-config.paths[3].methods[4].method=DELETE
keycloak.policy-enforcer-config.paths[3].methods[4].scopes[0]=provisioningtags_delete

# Technical Parameter API
keycloak.policy-enforcer-config.paths[4].path=/private/auth/technicalparameters/*
keycloak.policy-enforcer-config.paths[4].methods[0].method=POST
keycloak.policy-enforcer-config.paths[4].methods[0].scopes[0]=technicalparameters_create
keycloak.policy-enforcer-config.paths[4].methods[1].method=GET
keycloak.policy-enforcer-config.paths[4].methods[1].scopes[0]=technicalparameters_read
keycloak.policy-enforcer-config.paths[4].methods[2].method=PUT
keycloak.policy-enforcer-config.paths[4].methods[2].scopes[0]=technicalparameters_update
keycloak.policy-enforcer-config.paths[4].methods[3].method=PATCH
keycloak.policy-enforcer-config.paths[4].methods[3].scopes[0]=technicalparameters_update
keycloak.policy-enforcer-config.paths[4].methods[4].method=DELETE
keycloak.policy-enforcer-config.paths[4].methods[4].scopes[0]=technicalparameters_delete

# Provisioning Action API
keycloak.policy-enforcer-config.paths[5].path=/private/auth/provisioningactions/*
keycloak.policy-enforcer-config.paths[5].methods[0].method=POST
keycloak.policy-enforcer-config.paths[5].methods[0].scopes[0]=provisioningactions_create
keycloak.policy-enforcer-config.paths[5].methods[1].method=GET
keycloak.policy-enforcer-config.paths[5].methods[1].scopes[0]=provisioningactions_read
keycloak.policy-enforcer-config.paths[5].methods[2].method=PUT
keycloak.policy-enforcer-config.paths[5].methods[2].scopes[0]=provisioningactions_update
keycloak.policy-enforcer-config.paths[5].methods[3].method=PATCH
keycloak.policy-enforcer-config.paths[5].methods[3].scopes[0]=provisioningactions_update
keycloak.policy-enforcer-config.paths[5].methods[4].method=DELETE
keycloak.policy-enforcer-config.paths[5].methods[4].scopes[0]=provisioningactions_delete

# Tag Activation API
keycloak.policy-enforcer-config.paths[6].path=/private/auth/tagactivationcodes/*
keycloak.policy-enforcer-config.paths[6].methods[0].method=POST
keycloak.policy-enforcer-config.paths[6].methods[0].scopes[0]=tagactivationcodes_create
keycloak.policy-enforcer-config.paths[6].methods[1].method=GET
keycloak.policy-enforcer-config.paths[6].methods[1].scopes[0]=tagactivationcodes_read
keycloak.policy-enforcer-config.paths[6].methods[2].method=PUT
keycloak.policy-enforcer-config.paths[6].methods[2].scopes[0]=tagactivationcodes_update
keycloak.policy-enforcer-config.paths[6].methods[3].method=PATCH
keycloak.policy-enforcer-config.paths[6].methods[3].scopes[0]=tagactivationcodes_update
keycloak.policy-enforcer-config.paths[6].methods[4].method=DELETE
keycloak.policy-enforcer-config.paths[6].methods[4].scopes[0]=tagactivationcodes_create

# Provisioning Action Parameter API
keycloak.policy-enforcer-config.paths[7].path=/private/auth/tagparametervalues/*
keycloak.policy-enforcer-config.paths[7].methods[0].method=POST
keycloak.policy-enforcer-config.paths[7].methods[0].scopes[0]=tagparametervalues_create
keycloak.policy-enforcer-config.paths[7].methods[1].method=GET
keycloak.policy-enforcer-config.paths[7].methods[1].scopes[0]=tagparametervalues_read
keycloak.policy-enforcer-config.paths[7].methods[2].method=PUT
keycloak.policy-enforcer-config.paths[7].methods[2].scopes[0]=tagparametervalues_update
keycloak.policy-enforcer-config.paths[7].methods[3].method=PATCH
keycloak.policy-enforcer-config.paths[7].methods[3].scopes[0]=tagparametervalues_update
keycloak.policy-enforcer-config.paths[7].methods[4].method=DELETE
keycloak.policy-enforcer-config.paths[7].methods[4].scopes[0]=tagparametervalues_delete

# Dashboard API
keycloak.policy-enforcer-config.paths[8].path=/private/auth/servicesDashboard
keycloak.policy-enforcer-config.paths[8].methods[0].method=GET
keycloak.policy-enforcer-config.paths[8].methods[0].scopes[0]=dashboard_read

# Importer API
keycloak.policy-enforcer-config.paths[9].path=/private/auth/import/*
keycloak.policy-enforcer-config.paths[9].methods[0].method=GET
keycloak.policy-enforcer-config.paths[9].methods[0].scopes[0]=import_read
keycloak.policy-enforcer-config.paths[9].methods[1].method=POST
keycloak.policy-enforcer-config.paths[9].methods[1].scopes[0]=import_write
keycloak.policy-enforcer-config.paths[9].methods[2].method=DELETE
keycloak.policy-enforcer-config.paths[9].methods[2].scopes[0]=import_delete

# Job API
keycloak.policy-enforcer-config.paths[10].path=/api/v1/private/auth/job/*
keycloak.policy-enforcer-config.paths[10].methods[0].method=POST
keycloak.policy-enforcer-config.paths[10].methods[0].scopes[0]=job_create
keycloak.policy-enforcer-config.paths[10].methods[1].method=GET
keycloak.policy-enforcer-config.paths[10].methods[1].scopes[0]=job_read
keycloak.policy-enforcer-config.paths[10].methods[2].method=PUT
keycloak.policy-enforcer-config.paths[10].methods[2].scopes[0]=job_update
keycloak.policy-enforcer-config.paths[10].methods[3].method=PATCH
keycloak.policy-enforcer-config.paths[10].methods[3].scopes[0]=job_update
keycloak.policy-enforcer-config.paths[10].methods[4].method=DELETE
keycloak.policy-enforcer-config.paths[10].methods[4].scopes[0]=job_delete